# Read token from master node1 and copy to config.yaml for other master nodes
- name: "Read a file content"
  shell: |
    cat /var/lib/rancher/rke2/server/token
  register: token
  when: "inventory_hostname in ['node1']"

- name: "Print the file content to a console"
  debug:
    msg: "{{ hostvars['node1']['token']['stdout'] }}"
  when: "inventory_hostname in ['node1']"

- name: Construct the config.yaml file content for nodeN
  set_fact:
    config_yaml_content: |
      token: {{ hostvars['node1']['token']['stdout'] }}      
      server: https://{{ rancher_hostname }}.{{ domain_name }}:9345
      tls-san:
        - {{ first_addition }}-{{ inventory_hostname }}
        - {{ first_addition }}-{{ inventory_hostname }}.{{ domain_name }}
        - {{ rancher_ip }}
        - {{ ansible_default_ipv4.address }}
        - {{ rancher_hostname }}.{{ domain_name }}
  when: "inventory_hostname in ['node2','node3']"

- name: Print content
  debug: var=config_yaml_content
  when: "inventory_hostname in ['node2','node3']"

- name: Copy content to /etc/rancher/rke2/config.yaml
  ansible.builtin.copy:
    content: "{{ config_yaml_content }}"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  when: "inventory_hostname in ['node2','node3']"

- name: Server node installation
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="{{ rke2_version }}" sh -
  register: setup_response
  when: "inventory_hostname in ['node2','node3']"

- name: Print setup response
  debug:
    var: setup_response
  when: "inventory_hostname in ['node2','node3']"

- name: Start and enable rke2 service
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: true
  register: server_response
  when: "inventory_hostname in ['node2','node3']"

- name: Print server response
  debug:
    var: server_response
  when: "inventory_hostname in ['node2','node3']"
